server:
  port: 8005

spring:
  application:
    name: auth-consumer-service

  boot:
    admin:
      client:
        url: "http://localhost:8000"


  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

