server:
  port: 9998
spring:
  application:
    name: auth-oauth2-jwt
  cloud:
    consul:
      host: localhost
      port: 8900
      discovery:
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s