server:
  port: 8501

spring:
  application:
    name: auth-hystrix
  cloud:
    consul:
      host: localhost
      port: 8900
      discovery:
        serviceName: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

turbine:
  instanceUrlSuffix: hystrix.stream #指定路劲
  appConfig: auth-consumer #指定收集监控信息的服务名
  clusterNameExpression: "'default'" #指定集群名称，若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true #默认为false 服务以host区分，设置为true则以host+port进行区分