server:
  port: 8020
spring:
  application:
    name: auth-config
  cloud:
    consul:
      host: localhost
      port: 8900
      discovery:
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s
    config:
      server:
        git:
          uri: https://gitee.com/huangjunjies/config-repo.git
          username: 1157510753@qq.com
          password: 123456226212+
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS